#!/bin/bash

# The following scripting is based upon a Pulsar tutorial for running Pulsar in Kubernetes on
# minikube. The url for the tuturial is:
# https://pulsar.apache.org/docs/4.0.x/getting-started-helm/

# Step 1 - Deploys and configures the following:
#            a) Deploys a fresh minikube with minikube addons (dashboard, metallb);
#            c) Configures Metallb loadbalancer
#            d) Deploys Kubernetes Gateway API CRDs (cert-manager deploy uses)
#            e) Deploys istio in Ambient mode.
#            f) Deploys Cert-Manager
#            g) Deploys Pulsar and all required components into the Cluster
#            h) Sets pulsar namespace to istio ambient mode which initiates mTLS between pods
#            f) Tests access from the Pulsar CLI client
#            g) Allows running of the simple java test program (eclipse, maven) found in the
#               pulsar-client directory within this project.

# This learning prototypes were developed and tested using the following:
#   a) Ubuntu                 - 20.04.6 LTS
#   b) Minikube               - 1.34.0
#   c) Kubernetes             - 1.31.0
#   d) Docker                 - 27.2.0
#   e) Metallb                - 0.9.6
#   f) Kubernetes Gateway API - 1.2.0
#   g) Istio (Ambient Mode)   - 1.23.2
#   h) Cert-Manager           - 1.15.5
#   i) Machine config - Processor - Intel® Core™ i7-7700K CPU @ 4.20GHz × 8 
#                       Memory    - 64 GB
#  
# Pulsar deployment
# The following deployment was initially generated by running a dry-run from the Pulsar
# minikube Helm chart as follows:
# helm install --dry-run --values ${PROTODIR}/helm/values-02.yaml --namespace pulsar pulsar-mini apache/pulsar > kube-pulsar.txt
# From this output the kube deployment components were obtained. This script does a minimal
# installation of only the main required Pulsar components.
#   Component   # Deployed
#    Zookeeper       3
#    Bookie          4
#    Toolset         1
#    Broker          3
#    Proxy           3
# Only the basic elements are deployed - so no PodMonitor, Prometheus, Graphana, PodDisrutpion, etc.
#
#################################################################################################
##### Note - Only if it has not already been installed to your dev machine do you need to do this step.
# Install pulsarctl from streamnative - Installs to $HOME/.pulsarctl
sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/streamnative/pulsarctl/master/install.sh)"
#################################################################################################
#         
# Open terminal 1
# Delete prior minikube ( if used and configured prior)
minikube delete -p services

# Start minikube - configure the settings to your requirements and hardware
# Note - normally I use kvm2 as the vm-driver. However istio cni in ambient mode does not
# currently work with kvm2 due to cni incompatibility. The work around is to use the 
# docker vm-driver.
minikube start -p services --cpus 3 --memory 12288 --vm-driver docker --cni kindnet --disk-size 100g

# Not really necessary as the minikube start configures kubectl to the servers instance.
minikube profile services

# Addons
minikube addons enable dashboard

# Deploy the addon loadbalancer metallb
minikube addons enable metallb

# Configure loadbalancer ip address range within the same range as the minikube ip
# The configuration is a start ip ( ie. 192.168.49.20 ) and an end ip that makes a 
# range of 10 ip addresses. The range should not overlap the minikube ip
minikube ip
minikube addons configure metallb
  -- Enter Load Balancer Start IP: 
  -- Enter Load Balancer End IP:

# Start dashboard
minikube dashboard

############## Open up a new (2nd) terminal ###################################
# Install the Kubernetes Gateway API CRDs (experimental also includes standard)
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml

# Install istio in ambient mode
istioctl install --set values.pilot.env.PILOT_ENABLE_ALPHA_GATEWAY_API=true --set profile=ambient --skip-confirmation

#### Install cert-manager with the following steps ####
# Create cert-manger namespace
kubectl create namespace cert-manager

# Deploy cert-manager gateway CRDs
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.5/cert-manager.crds.yaml

# Deploy cert-manager with gateway api enabled including the experimental gateway apis
helm install cert-manager --version 1.15 jetstack/cert-manager --namespace cert-manager \
  --set config.apiVersion="controller.config.cert-manager.io/v1alpha1" \
  --set config.kind="ControllerConfiguration" \
  --set config.enableGatewayAPI=true \
  --set "extraArgs={--feature-gates=ExperimentalGatewayAPISupport=true}"

# Project Directory
PROTODIR=/media/tim/ExtraDrive1/Projects/services/deploy

# Switch to Servers cluster to obtain the pulsar proxy tls certs.
minikube profile servers

kubectl get secret pulsar-tls-proxy -n pulsar -o "jsonpath={.data['ca\.crt']}" | base64 -d > $PROTODIR/gen/ca.crt
kubectl get secret pulsar-tls-proxy -n pulsar -o "jsonpath={.data['tls\.crt']}" | base64 -d > $PROTODIR/gen/tls.crt

PROXY_HOST=$(kubectl get svc -n pulsar pulsar-proxy --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
echo $PROXY_HOST

PROXY_URL="pulsar+ssl://$PROXY_HOST:6651"

# Switch back to services cluster
minikube profile services
kubectl create secret generic pulsar-client-tls --from-file=$PROTODIR/gen/tls.crt --from-file=$PROTODIR/gen/ca.crt


cat > ${PROTODIR}/kube-metadata/metadata-configmap.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: "metadata-svc-config"
data:
  kubeClusterName: "services"
  pulsarUseTLS:    "true"
  pulsarUrl:       $PROXY_URL
  tls-secret:      "pulsar-client-tls"   # Must match secret name which contains ca.crt and ca.crt
  caCertFilePath:  "app/certs/ca.crt"    # Must match volume mount
EOF


