apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  labels:
    app: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-sa
      containers:
      - name: watcher
        image: library/watcher:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
#        volumeMounts:
#        - name: ca-cert-vol
#          mountPath: /app/certs/ca
#          readOnly: true
#        - name: proxy-tls-vol
#          mountPath: /app/certs/tls
#          readOnly: true
        volumeMounts:
        - name: watcher-config
          mountPath: /app/config
          readOnly: true
        - mountPath: "/app/certs/tls"
          name: proxy-certs
          readOnly: true
      volumes:
      - name: proxy-certs
        secret:
          secretName: "pulsar-tls-proxy"
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt 
      - name: watcher-config
        configMap:
          name: watcher-config
 