apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-svc
  labels:
    app: metadata-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-svc
  template:
    metadata:
      labels:
        app: metadata-svc
    spec:
#      hostNetwork: true  # This allows access to host ports
#      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: metadata-svc-sa
      containers:
      - name: metadata-svc
        image: library/metadatasvc:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONFIG_MAP_NAME
          value: "metadata-svc-config"
        - name: SHARED_SECRET_PATH
          value: "/app/data/shared-secrets.json"
        volumeMounts:
        - name: metadata-svc-config
          mountPath: /app/config
          readOnly: true
        - mountPath: "/app/certs"
          name: proxy-certs
          readOnly: true
        - name: avro-schemas
          mountPath: "/app/avro-schemas"
          readOnly: true
        - name: shared-secrets-volume
          mountPath: /app/data
          readOnly: false
      volumes:
      - name: proxy-certs
        secret:
          secretName: "pulsar-client-tls"
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt 
      - name: metadata-svc-config
        configMap:
          name: metadata-svc-config
      - name: avro-schemas
        configMap:
          name: avro-schemas
      - name: shared-secrets-volume
        persistentVolumeClaim:
          claimName: shared-secrets-pvc
 
